domain_path: F:\Project_IDAQclone\Project_IDAQ\Software_Space\AD7328_Space\AD7328_PRT\zynq_fsbl\zynq_fsbl_bsp
app_src_dir: D:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
