set_property PACKAGE_PIN J14 [get_ports CLK_IN1_D_0_clk_p]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports CLK_IN1_D_0_clk_p]
set_property PACKAGE_PIN Y12 [get_ports sys_rst_0]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_0]

set_property PACKAGE_PIN F13 [get_ports {ctrlr_reg_0[0]}]
set_property PACKAGE_PIN E11 [get_ports {ctrlr_reg_0[1]}]
set_property PACKAGE_PIN E10 [get_ports {ctrlr_reg_0[2]}]
set_property PACKAGE_PIN G12 [get_ports {ctrlr_reg_0[3]}]
set_property PACKAGE_PIN G10 [get_ports {ctrlr_reg_0[4]}]
set_property PACKAGE_PIN H13 [get_ports {ctrlr_reg_0[5]}]
set_property PACKAGE_PIN K15 [get_ports {ctrlr_reg_0[6]}]
set_property PACKAGE_PIN K13 [get_ports {ctrlr_reg_0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[0]}]
set_property PACKAGE_PIN B17 [get_ports {led_out_0[0]}]
set_property PACKAGE_PIN B16 [get_ports {led_out_0[1]}]
set_property PACKAGE_PIN A15 [get_ports {led_out_0[2]}]
set_property PACKAGE_PIN C14 [get_ports {led_out_0[3]}]
set_property PACKAGE_PIN A13 [get_ports {led_out_0[4]}]
set_property PACKAGE_PIN D13 [get_ports {led_out_0[5]}]
set_property PACKAGE_PIN C12 [get_ports {led_out_0[6]}]
set_property PACKAGE_PIN C11 [get_ports {led_out_0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[0]}]

## ---------------- DAC 1 ----------------
set_property PACKAGE_PIN B7  [get_ports {ad3542_rst_0[0]}]
set_property PACKAGE_PIN A8  [get_ports {ad3542_ldac_0[0]}]
set_property PACKAGE_PIN A10 [get_ports {ad3542_cs_0[0]}]
set_property PACKAGE_PIN F8  [get_ports {ad3542_sclk_0[0]}]
set_property PACKAGE_PIN B10 [get_ports {ad3542_sdi_0[0]}]
set_property PACKAGE_PIN A9  [get_ports {ad3542_sdo_0[0]}]

# ---------------- DAC 2 ----------------
set_property PACKAGE_PIN D8 [get_ports {ad3542_rst_0[1]}]
set_property PACKAGE_PIN B4 [get_ports {ad3542_ldac_0[1]}]
set_property PACKAGE_PIN A5 [get_ports {ad3542_cs_0[1]}]
set_property PACKAGE_PIN G7 [get_ports {ad3542_sclk_0[1]}]
set_property PACKAGE_PIN A4 [get_ports {ad3542_sdi_0[1]}]
set_property PACKAGE_PIN B5 [get_ports {ad3542_sdo_0[1]}]

## ---------------- DAC 3 ----------------
set_property PACKAGE_PIN F5 [get_ports {ad3542_rst_0[2]}]
set_property PACKAGE_PIN F9 [get_ports {ad3542_ldac_0[2]}]
set_property PACKAGE_PIN B6 [get_ports {ad3542_cs_0[2]}]
set_property PACKAGE_PIN C8 [get_ports {ad3542_sclk_0[2]}]
set_property PACKAGE_PIN E5 [get_ports {ad3542_sdi_0[2]}]
set_property PACKAGE_PIN D9 [get_ports {ad3542_sdo_0[2]}]

## ---------------- DAC 4 ----------------
set_property PACKAGE_PIN H6  [get_ports {ad3542_rst_0[3]}]
set_property PACKAGE_PIN J8  [get_ports {ad3542_ldac_0[3]}]
set_property PACKAGE_PIN J10 [get_ports {ad3542_cs_0[3]}]
set_property PACKAGE_PIN D6  [get_ports {ad3542_sclk_0[3]}]
set_property PACKAGE_PIN H7  [get_ports {ad3542_sdi_0[3]}]
set_property PACKAGE_PIN J9  [get_ports {ad3542_sdo_0[3]}]


# -------- I/O Standard (All DAC Signals) --------
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_rst_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_ldac_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_cs_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_sclk_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_sdi_0[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_sdo_0[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_rst_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_ldac_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_cs_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_sclk_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_sdi_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_sdo_0[1]}]

set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_rst_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_ldac_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_cs_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_sclk_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_sdi_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_sdo_0[2]}]

set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_rst_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_ldac_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_cs_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_sclk_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_sdi_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ad3542_sdo_0[3]}]