set_property PACKAGE_PIN J14 [get_ports CLK_IN1_D_0_clk_p]
set_property PACKAGE_PIN H14 [get_ports CLK_IN1_D_0_clk_n]
set_property IOSTANDARD DIFF_HSTL_II_18 [get_ports CLK_IN1_D_0_clk_p]
set_property PACKAGE_PIN Y12 [get_ports sys_rst_0]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_0]
set_property PACKAGE_PIN F13 [get_ports {ctrlr_reg_0[0]}]
set_property PACKAGE_PIN E11 [get_ports {ctrlr_reg_0[1]}]
set_property PACKAGE_PIN E10 [get_ports {ctrlr_reg_0[2]}]
set_property PACKAGE_PIN G12 [get_ports {ctrlr_reg_0[3]}]
set_property PACKAGE_PIN G10 [get_ports {ctrlr_reg_0[4]}]
set_property PACKAGE_PIN H13 [get_ports {ctrlr_reg_0[5]}]
set_property PACKAGE_PIN K15 [get_ports {ctrlr_reg_0[6]}]
set_property PACKAGE_PIN K13 [get_ports {ctrlr_reg_0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {ctrlr_reg_0[0]}]
set_property PACKAGE_PIN B17 [get_ports {led_out_0[0]}]
set_property PACKAGE_PIN B16 [get_ports {led_out_0[1]}]
set_property PACKAGE_PIN A15 [get_ports {led_out_0[2]}]
set_property PACKAGE_PIN C14 [get_ports {led_out_0[3]}]
set_property PACKAGE_PIN A13 [get_ports {led_out_0[4]}]
set_property PACKAGE_PIN D13 [get_ports {led_out_0[5]}]
set_property PACKAGE_PIN C12 [get_ports {led_out_0[6]}]
set_property PACKAGE_PIN C11 [get_ports {led_out_0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led_out_0[0]}]

# ---------------- AD7328-3 ----------------
set_property PACKAGE_PIN AA20 [get_ports ad7328_cs_0]
set_property PACKAGE_PIN AA19 [get_ports ad7328_sclk_0]
set_property PACKAGE_PIN AB21 [get_ports ad7328_sdi_0]
set_property PACKAGE_PIN W18  [get_ports ad7328_sdo_0]

## ---------------- AD7328-4 ----------------
#set_property PACKAGE_PIN AF19 [get_ports ad7328_cs_0]
#set_property PACKAGE_PIN AC18 [get_ports ad7328_sclk_0]
#set_property PACKAGE_PIN AD20 [get_ports ad7328_sdi_0]
#set_property PACKAGE_PIN AB22 [get_ports ad7328_sdo_0]

## ---------------- AD7328-5 ----------------
#set_property PACKAGE_PIN AD24 [get_ports ad7328_cs_0]
#set_property PACKAGE_PIN AA23 [get_ports ad7328_sclk_0]
#set_property PACKAGE_PIN AC24 [get_ports ad7328_sdi_0]
#set_property PACKAGE_PIN AC23 [get_ports ad7328_sdo_0]

# -------- I/O Standard (All AD7328 Signals) --------
set_property IOSTANDARD LVCMOS33 [get_ports ad7328_cs_0]
set_property IOSTANDARD LVCMOS33 [get_ports ad7328_sclk_0]
set_property IOSTANDARD LVCMOS33 [get_ports ad7328_sdi_0]
set_property IOSTANDARD LVCMOS33 [get_ports ad7328_sdo_0]

