domain_path: F:\Project_IDAQclone\Project_IDAQ\Software_Space\IDAQ_Space\IDAQ_Pltfrm\export\IDAQ_Pltfrm\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
